/*
 * ============================================================
 * Android AI Assistant (Enterprise Edition)
 * ============================================================
 * Module     : data
 * File       : MeetingApiService.kt
 * Purpose    : Retrofit service interface for the Meeting / Transcription_Service REST
 *              endpoints used by the Meeting Assistant feature.
 *
 * Architecture Layer : Data
 * Pattern Used       : Retrofit API Service Interface
 *
 * Dependencies: Retrofit, kotlinx.serialization
 * Requirements: 19.1, 5.6
 * ============================================================
 */
package com.aiassistant.data.remote.meeting

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import retrofit2.http.Body
import retrofit2.http.GET
import retrofit2.http.POST
import retrofit2.http.Path

// ─── DTOs ─────────────────────────────────────────────────────────────────────

/**
 * Request body for `POST /meeting/start`.
 *
 * @param userId The authenticated user's identifier. Used to associate the session
 *               with the correct account on the Transcription_Service.
 */
@Serializable
data class MeetingStartRequest(
    @SerialName("user_id") val userId: String
)

/**
 * Response from `POST /meeting/start`.
 *
 * @param sessionId Opaque session identifier generated by the Transcription_Service.
 *                  Must be supplied to subsequent stop and summary calls.
 */
@Serializable
data class MeetingStartResponse(
    @SerialName("session_id") val sessionId: String
)

/**
 * Request body for `POST /meeting/{sessionId}/stop`.
 *
 * The request body is intentionally empty; the session is identified by the path
 * parameter. The backend finalises the audio stream and queues it for transcription.
 */
@Serializable
data class MeetingStopRequest(
    @SerialName("session_id") val sessionId: String
)

/**
 * Response from `POST /meeting/{sessionId}/stop`.
 *
 * @param queued True when audio has been accepted by the transcription queue.
 */
@Serializable
data class MeetingStopResponse(
    @SerialName("queued") val queued: Boolean
)

/**
 * Response from `GET /meeting/{sessionId}/summary`.
 *
 * @param summary Full AI-generated summary text (Markdown), including transcript with
 *                speaker labels and extracted action items.
 */
@Serializable
data class MeetingSummaryResponse(
    @SerialName("summary") val summary: String
)

// ─── Retrofit service ─────────────────────────────────────────────────────────

/**
 * Retrofit service for meeting recording and transcription endpoints.
 *
 * Consumed exclusively by [MeetingRemoteDataSource].
 */
interface MeetingApiService {

    /**
     * Opens a new recording session on the Transcription_Service (Requirement 19.1).
     *
     * @param body Request containing the authenticated user's ID.
     * @return Response containing the new session identifier.
     */
    @POST("meeting/start")
    suspend fun startMeeting(@Body body: MeetingStartRequest): MeetingStartResponse

    /**
     * Signals the Transcription_Service that recording has stopped and audio is ready
     * for processing (Requirement 19.1).
     *
     * @param sessionId Path parameter — the session to stop.
     * @param body      Request body carrying the session ID for server-side validation.
     * @return Response confirming audio has been accepted into the transcription queue.
     */
    @POST("meeting/{sessionId}/stop")
    suspend fun stopMeeting(
        @Path("sessionId") sessionId: String,
        @Body body: MeetingStopRequest
    ): MeetingStopResponse

    /**
     * Retrieves the completed AI-generated meeting summary (Requirement 19.1).
     *
     * Should only be called after [stopMeeting] returns successfully and the backend
     * has finished transcription. The caller (ViewModel) is responsible for any
     * polling logic before calling this endpoint.
     *
     * @param sessionId Path parameter — the session whose summary to fetch.
     * @return Response containing the full Markdown summary text.
     */
    @GET("meeting/{sessionId}/summary")
    suspend fun getMeetingSummary(
        @Path("sessionId") sessionId: String
    ): MeetingSummaryResponse
}
