steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - '$_IMAGE'
      - '.'
images:
  - '$_IMAGE'
substitutions:
  _IMAGE: 'asia-south1-docker.pkg.dev/android-ai-assistant-89cec/backend/ai-assistant-backend:sha-9487a10'
options:
  logging: CLOUD_LOGGING_ONLY
