/**
 * SessionManager.kt — core-common module
 *
 * Purpose: Generates and manages the identifiers that link related observability
 *          events together across a single app session and user action trace.
 *
 * Architecture: core-common — pure Kotlin, zero Android/framework dependencies.
 *               Injected as a singleton by ObservabilityModule; can be instantiated
 *               directly in unit tests.
 *
 * Identifiers managed:
 *
 *   sessionId  — Assigned once at construction (i.e. app launch / process start).
 *                Groups all [ObservabilityEvent] instances within a single
 *                foreground-to-background lifecycle. Stable for the process lifetime.
 *
 *   traceId    — Scoped to one logical user action (e.g. "tap Send → network call →
 *                render response"). Callers start a new trace with [beginTrace] and
 *                end it with [endTrace]. The current trace ID is automatically
 *                attached to network requests via [NetworkObservabilityInterceptor].
 *
 *   requestId  — Unique per outgoing HTTP request. Generated fresh by
 *                [newRequestId]; never stored — callers are responsible for passing
 *                it through the network layer and including it in the event.
 *
 * Design decisions:
 * - UUID v4 (random) is used for all identifiers. Timestamps embedded in UUIDs
 *   (v1, v7) offer no additional benefit here — the [ObservabilityEvent.timestamp]
 *   field already carries capture time.
 * - [currentTraceId] is held in an [AtomicReference] so [beginTrace] / [endTrace]
 *   are safe to call from any thread (including OkHttp I/O threads) without a lock.
 * - [sessionId] is val — immutable after construction, so no synchronization needed.
 *
 * Phase 2 — Android Observability
 */

package com.aiassistant.core.common.observability

import java.util.UUID
import java.util.concurrent.atomic.AtomicReference

/**
 * Generates and vends the correlation identifiers used by the observability layer.
 *
 * ### Lifecycle of each identifier
 *
 * | Identifier   | Scope                  | Generated by         |
 * |--------------|------------------------|----------------------|
 * | [sessionId]  | Process lifetime       | Construction time    |
 * | [traceId]    | One logical user flow  | [beginTrace]         |
 * | requestId    | One HTTP request       | [newRequestId]       |
 *
 * Usage example (in a ViewModel or UseCase):
 * ```kotlin
 * sessionManager.beginTrace()
 * try {
 *     val result = repository.sendMessage(text)   // network call tagged with traceId
 * } finally {
 *     sessionManager.endTrace()
 * }
 * ```
 *
 * The network interceptor reads [currentTraceId] automatically — callers don't need to
 * pass it explicitly to repository or network layer.
 */
class SessionManager {

    // ─── Session ID ───────────────────────────────────────────────────────────

    /**
     * Stable identifier for the current app session (process lifetime).
     *
     * Assigned once at construction. A new session ID is generated each time the
     * app process starts — it is NOT persisted to disk.
     */
    val sessionId: String = UUID.randomUUID().toString()

    // ─── Trace ID ─────────────────────────────────────────────────────────────

    /**
     * Holds the active trace ID, or `null` when no trace is in progress.
     *
     * [AtomicReference] ensures that reads and writes from different threads
     * (ViewModel thread, OkHttp I/O thread) are always consistent without a lock.
     */
    private val _currentTraceId = AtomicReference<String?>(null)

    /**
     * The trace ID currently active, or `null` if no trace has been started.
     *
     * Read by [NetworkObservabilityInterceptor] to tag outgoing requests.
     */
    val currentTraceId: String? get() = _currentTraceId.get()

    /**
     * Starts a new trace, replacing any previously active trace.
     *
     * Call this at the beginning of a logical user action (e.g. when the user taps
     * a button that triggers one or more API calls). All [ObservabilityEvent]
     * instances captured until [endTrace] is called will share the same [traceId].
     *
     * @return The new trace ID, in case the caller needs to store it locally.
     */
    fun beginTrace(): String {
        val id = UUID.randomUUID().toString()
        _currentTraceId.set(id)
        return id
    }

    /**
     * Ends the current trace, setting [currentTraceId] back to `null`.
     *
     * Idempotent — safe to call even if no trace is currently active.
     */
    fun endTrace() {
        _currentTraceId.set(null)
    }

    // ─── Request ID ───────────────────────────────────────────────────────────

    /**
     * Generates a new, unique request ID for a single outgoing HTTP call.
     *
     * Called by [NetworkObservabilityInterceptor] once per request. The returned ID
     * is attached to the request as the `X-Request-ID` header so the backend can
     * correlate its log entries with the Android-side [ObservabilityEvent].
     *
     * @return A UUID v4 string.
     */
    fun newRequestId(): String = UUID.randomUUID().toString()
}
