/**
 * BuildConfigEnvironmentConfig.kt — core-network module
 *
 * Purpose: [EnvironmentConfig] implementation backed by the flavor-specific
 *          [BuildConfig] fields generated by `core-network/build.gradle.kts`.
 *
 * Architecture:
 *   - Lives in core-network so it can read this module's own BuildConfig without
 *     creating a cross-module dependency.
 *   - Instantiated by `app/di/EnvironmentModule` via Hilt so the single
 *     [EnvironmentConfig] singleton is scoped to [dagger.hilt.components.SingletonComponent].
 *   - All fields are read once at construction time — the object is effectively
 *     a stateless value carrier backed by compile-time constants.
 *
 * NOTE: Do NOT add business logic or runtime conditions here. This class must remain
 * a pure data holder. Environment-specific behaviour belongs in the consumers that
 * depend on [EnvironmentConfig].
 */
package com.aiassistant.core.network

/**
 * Reads environment values from the flavor-aware [BuildConfig] generated by
 * `core-network/build.gradle.kts`.
 *
 * The `BuildConfig` fields are set per product flavor in Gradle:
 *
 * | Flavor     | API_BASE_URL                               | WS_BASE_URL                            | IS_PRODUCTION | IS_LOCAL |
 * |------------|--------------------------------------------|----------------------------------------|---------------|----------|
 * | local      | http://10.0.2.2:8080/                      | ws://10.0.2.2:8080                     | false         | true     |
 * | stage      | https://api-stage.aiassistant.example.com/ | wss://ws-stage.aiassistant.example.com | false         | false    |
 * | production | https://ai-assistant-backend-106071012091..| wss://ws.aiassistant.example.com       | true          | false    |
 *
 * Constructor is package-accessible — instantiated only by the Hilt EnvironmentModule in :app.
 * Tests instantiate [FakeEnvironmentConfig] (in core-network test sources) instead.
 */
class BuildConfigEnvironmentConfig : EnvironmentConfig {

    override val apiBaseUrl: String
        get() = BuildConfig.API_BASE_URL

    override val websocketUrl: String
        get() = BuildConfig.WS_BASE_URL

    override val isProduction: Boolean
        get() = BuildConfig.IS_PRODUCTION

    override val isLocal: Boolean
        get() = BuildConfig.IS_LOCAL

    override val isStage: Boolean
        get() = !BuildConfig.IS_PRODUCTION && !BuildConfig.IS_LOCAL

    override val environmentName: String
        get() = when {
            BuildConfig.IS_LOCAL      -> "local"
            BuildConfig.IS_PRODUCTION -> "production"
            else                      -> "stage"
        }
}
