"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
# Migration script template for Alembic.
# Generated by: alembic revision --autogenerate -m "<description>"
#
# Requirements: 9.3, 9.10
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
${imports if imports else ""}
from alembic import op

# ---------------------------------------------------------------------------
# Revision identifiers, used by Alembic.
# ---------------------------------------------------------------------------

revision: str = ${repr(up_revision)}
down_revision: Union[str, None] = ${repr(down_revision)}
branch_labels: Union[str, Sequence[str], None] = ${repr(branch_labels)}
depends_on: Union[str, Sequence[str], None] = ${repr(depends_on)}


def upgrade() -> None:
    """Apply the migration changes to the database schema."""
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    """Revert the migration changes from the database schema."""
    ${downgrades if downgrades else "pass"}
