/*
 * ============================================================
 * Android AI Assistant (Enterprise Edition)
 * ============================================================
 * Module     : core-ui
 * File       : components/AiModeIndicator.kt
 * Purpose    : Reusable AI mode pill chip — communicates whether a response
 *              was generated by On-device Gemma, Cloud AI, or RAG.
 *
 * Architecture Layer : Core-UI — shared design system.
 *                      Consumed by feature-chat, feature-on-device-rag,
 *                      feature-rag, and feature-on-device-ai screens.
 *                      Never imported from domain or data layers.
 *
 * Design Decision    : Each mode gets a distinct icon AND a distinct container
 *                      color so the mode is never communicated by color alone
 *                      (WCAG 1.4.1 / requirement 23.4).
 *                      The chip is intentionally compact (labelSmall) and
 *                      subtle so it does not distract from the conversation.
 *
 * Requirements       : 7.1–7.3, 23.4
 * ============================================================
 */
package com.aiassistant.core.ui.components

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.aiassistant.core.ui.AppColors
import com.aiassistant.core.ui.AppIcons
import com.aiassistant.core.ui.AppShapes
import com.aiassistant.core.ui.AppTheme
import com.aiassistant.core.ui.spacing

/** The AI inference mode being represented. */
enum class AiMode {
    /** On-device Gemma inference — private, offline-capable. */
    GEMMA,

    /** Cloud AI inference — requires network. */
    CLOUD,

    /**
     * Retrieval-Augmented Generation — cloud inference grounded in
     * the user's document corpus.
     */
    RAG,

    /**
     * On-device RAG — local document retrieval + on-device inference.
     */
    ON_DEVICE_RAG
}

/**
 * A compact pill-shaped chip indicating the AI mode used for a response.
 *
 * Place this above the first assistant message bubble in a turn, or inline
 * in a TopAppBar subtitle slot.
 *
 * @param mode               The [AiMode] to represent.
 * @param modifier           Applied to the root [Surface].
 * @param showLabel          When `false`, only the icon is shown (useful in
 *                           very compact contexts like TopAppBar subtitles).
 */
@Composable
fun AiModeIndicator(
    mode: AiMode,
    modifier: Modifier = Modifier,
    showLabel: Boolean = true
) {
    val isDark = isSystemInDarkTheme()
    val config = aiModeConfig(mode, isDark)

    Surface(
        modifier = modifier.semantics {
            contentDescription = config.accessibilityLabel
        },
        color = config.containerColor,
        shape = AppShapes.pill,
        tonalElevation = 0.dp
    ) {
        Row(
            modifier = Modifier.padding(
                horizontal = if (showLabel) 8.dp else 6.dp,
                vertical = 3.dp
            ),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.Center
        ) {
            Icon(
                imageVector = config.icon,
                contentDescription = null, // described by parent semantics
                tint = config.onContainerColor,
                modifier = Modifier.size(11.dp)
            )
            if (showLabel) {
                Spacer(modifier = Modifier.width(3.dp))
                Text(
                    text = config.label,
                    style = MaterialTheme.typography.labelSmall,
                    color = config.onContainerColor
                )
            }
        }
    }
}

// ── Config data class ─────────────────────────────────────────────────────────

private data class AiModeConfig(
    val icon: androidx.compose.ui.graphics.vector.ImageVector,
    val label: String,
    val containerColor: Color,
    val onContainerColor: Color,
    val accessibilityLabel: String
)

private fun aiModeConfig(mode: AiMode, isDark: Boolean): AiModeConfig = when (mode) {
    AiMode.GEMMA -> AiModeConfig(
        icon = AppIcons.Ai.Gemma,
        label = "Gemma",
        containerColor = if (isDark) AppColors.gemmaContainerDark else AppColors.gemmaContainerLight,
        onContainerColor = if (isDark) AppColors.gemmaOnContainerDark else AppColors.gemmaOnContainerLight,
        accessibilityLabel = "On-device Gemma"
    )
    AiMode.CLOUD -> AiModeConfig(
        icon = AppIcons.Ai.Cloud,
        label = "Cloud AI",
        containerColor = if (isDark) AppColors.cloudContainerDark else AppColors.cloudContainerLight,
        onContainerColor = if (isDark) AppColors.cloudOnContainerDark else AppColors.cloudOnContainerLight,
        accessibilityLabel = "Cloud AI"
    )
    AiMode.RAG -> AiModeConfig(
        icon = AppIcons.Ai.Rag,
        label = "RAG",
        containerColor = if (isDark) AppColors.ragContainerDark else AppColors.ragContainerLight,
        onContainerColor = if (isDark) AppColors.ragOnContainerDark else AppColors.ragOnContainerLight,
        accessibilityLabel = "RAG — document-grounded response"
    )
    AiMode.ON_DEVICE_RAG -> AiModeConfig(
        icon = AppIcons.Ai.Gemma,
        label = "On-device RAG",
        containerColor = if (isDark) AppColors.gemmaContainerDark else AppColors.gemmaContainerLight,
        onContainerColor = if (isDark) AppColors.gemmaOnContainerDark else AppColors.gemmaOnContainerLight,
        accessibilityLabel = "On-device RAG"
    )
}

// ── Helper extension ──────────────────────────────────────────────────────────

/** Maps a provider string from the domain layer to an [AiMode]. */
fun String?.toAiMode(): AiMode = when (this?.lowercase()) {
    "gemma", "on_device", "on-device" -> AiMode.GEMMA
    "rag", "cloud_rag"                -> AiMode.RAG
    "on_device_rag"                   -> AiMode.ON_DEVICE_RAG
    else                              -> AiMode.CLOUD
}

// ── Previews ──────────────────────────────────────────────────────────────────

@Preview(showBackground = true)
@Composable
private fun AiModeIndicatorGemmaPreview() {
    AppTheme(dynamicColor = false) {
        Row(
            modifier = Modifier.padding(8.dp),
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            AiModeIndicator(mode = AiMode.GEMMA)
            AiModeIndicator(mode = AiMode.CLOUD)
            AiModeIndicator(mode = AiMode.RAG)
            AiModeIndicator(mode = AiMode.ON_DEVICE_RAG)
        }
    }
}
