/*
 * ============================================================
 * Android AI Assistant (Enterprise Edition)
 * ============================================================
 * Module     : domain
 * File       : NoteRepository.kt
 * Purpose    : Domain contract defining data access operations for Note entities
 *
 * Architecture Layer : Domain
 * Pattern Used       : Repository Interface
 *
 * Key Concepts:
 *   - Clean Architecture with strict layer separation
 *   - Hilt dependency injection
 *
 * Dependencies:
 *   - See import statements below
 * ============================================================
 */

/*
 * ============================================================
 * Android AI Assistant (Enterprise Edition)
 * ============================================================
 * Module     : domain
 * File       : NoteRepository.kt
 * Purpose    : Domain contract defining data access operations for Note entities
 *
 * Architecture Layer : Domain
 * Pattern Used       : Repository Interface
 *
 * Key Concepts:
 *   - Clean Architecture with strict layer separation
 *   - Hilt dependency injection
 *
 * Dependencies:
 *   - See import statements below
 * ============================================================
 */
/**
 * NoteRepository.kt
 *
 * Purpose: Domain-layer repository interface for notes operations.
 *          Implemented in the data module; injected into use cases at runtime.
 * Architecture: domain module â€” pure Kotlin, zero Android or third-party framework dependencies.
 * Dependencies: core-common (ApiResult), domain model (Note)
 *
 * Requirements: 13.1, 13.2, 13.4, 13.5, 19.2
 */

package com.aiassistant.domain.repository

import com.aiassistant.core.common.ApiResult
import com.aiassistant.domain.model.Note
import kotlinx.coroutines.flow.Flow

/**
 * Contract for notes operations between the domain and data layers.
 *
 * The data module provides a concrete implementation backed by Room (local source of truth)
 * and Retrofit (remote sync). Notes always emit from the local cache first, following the
 * offline-first pattern (Requirement 13.4).
 */
interface NoteRepository {

    /**
     * Returns a [Flow] of all notes belonging to the authenticated user, sorted by
     * [Note.updatedAt] descending.
     *
     * @return Cold [Flow] emitting [ApiResult.Success] with the full notes list.
     */
    fun getNotes(): Flow<ApiResult<List<Note>>>

    /**
     * Returns a [Flow] of notes filtered by the given [tag] (Requirement 13.5).
     *
     * Only notes whose [Note.tags] list contains [tag] are included in the emission.
     *
     * @param tag The tag label to filter by. Pass an empty string to return all notes.
     * @return Cold [Flow] emitting [ApiResult.Success] with the filtered notes list.
     */
    fun getNotesByTag(tag: String): Flow<ApiResult<List<Note>>>

    /**
     * Creates or updates a note in the local Room database, then syncs to the backend
     * when connectivity is available.
     *
     * For a new note, pass a [Note] with a newly generated [Note.id]. For an update,
     * pass the existing [Note] with modified fields. The [Note.syncStatus] is set to
     * [com.aiassistant.domain.model.SyncStatus.PENDING] until the backend confirms.
     *
     * @param note The note to save.
     * @return [ApiResult.Success] with the persisted [Note] on success.
     */
    suspend fun saveNote(note: Note): ApiResult<Note>

    /**
     * Permanently deletes a note from the local database and the backend.
     *
     * @param noteId The unique identifier of the note to delete.
     * @return [ApiResult.Success] with [Unit] on success.
     */
    suspend fun deleteNote(noteId: String): ApiResult<Unit>

    /**
     * Requests an AI-generated summary of the given note's content.
     *
     * The summary is generated by the AI Orchestrator and SHALL contain no more than
     * 150 words while preserving all key facts (Requirement 13.2).
     *
     * @param noteId The unique identifier of the note to summarise.
     * @return [ApiResult.Success] with the summary text (â‰¤150 words) on success.
     */
    suspend fun summarizeNote(noteId: String): ApiResult<String>

    /**
     * Requests an AI rewrite of the given note in the user's learned writing style
     * (from the Memory Service) or neutral professional style as fallback.
     *
     * @param noteId The unique identifier of the note to rewrite.
     * @return [ApiResult.Success] with the rewritten note content on success.
     */
    suspend fun rewriteNote(noteId: String): ApiResult<String>
}
