# ============================================================
# Android AI Assistant (Enterprise Edition) — Backend
# ============================================================
# Module  : agents
# File    : llm_client.py
# Purpose : Provider-independent LLMClient interface + adapters that wrap
#           existing LLMProvider / LLMService without rewriting them.
#
# Architecture Layer : Agent Core (Phase 2)
# Pattern Used       : Adapter / Strategy
#
# Key Concepts:
#   - LLMClient is the agent layer's own thin interface; it does NOT replace
#     app.llm.base.LLMProvider which remains unchanged
#   - Two adapters:
#       LLMServiceAdapter   — wraps existing LLMService singleton (cloud)
#       LocalGemmaAdapter   — wraps LocalGemmaProvider (on-device / local)
#   - generate() for non-streaming completions
#   - stream() for incremental token delivery (async generator)
#   - LLMClientError is the typed error surface for the agent layer
#
# Dependencies: app.llm.base, app.llm.service, app.llm.exceptions,
#               app.agents.models (AgentCapability)
# ============================================================

"""LLMClient — provider-independent interface for agent LLM calls."""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from collections.abc import AsyncIterator

logger = logging.getLogger(__name__)


class LLMClientError(Exception):
    """Raised by LLMClient on unrecoverable failure.

    Attributes:
        provider:  Name of the provider that raised the error.
        retryable: True when a retry may succeed (transient error).
    """

    def __init__(
        self,
        message: str,
        provider: str = "",
        retryable: bool = False,
    ) -> None:
        super().__init__(message)
        self.provider = provider
        self.retryable = retryable


class LLMClient(ABC):
    """Provider-independent contract for generating LLM completions.

    Agent implementations depend only on this interface — not on GeminiProvider,
    OpenAIClient, or any other concrete class.

    ## Implementing an adapter

    ```python
    class MyAdapter(LLMClient):
        @property
        def provider_name(self) -> str:
            return "my_provider"

        @property
        def is_available(self) -> bool:
            return True

        async def generate(self, prompt: str, **kwargs) -> str:
            ...

        async def stream(self, prompt: str, **kwargs) -> AsyncIterator[str]:
            ...
    ```
    """

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Canonical provider identifier (e.g. ``"gemini"``, ``"gemma"``).

        Matches the existing ``LlmProvider.id`` values used on Android.
        """

    @property
    @abstractmethod
    def is_available(self) -> bool:
        """True when this client can currently serve requests."""

    @abstractmethod
    async def generate(
        self,
        prompt: str,
        *,
        system_prompt: str = "",
        conversation_id: str | None = None,
        user_id: str | None = None,
        max_tokens: int | None = None,
        temperature: float | None = None,
        rag_context: list[str] | None = None,
    ) -> str:
        """Generate a complete (non-streaming) text response.

        Args:
            prompt:          The user's message or assembled agent prompt.
            system_prompt:   Optional system / persona instruction.
            conversation_id: Identifier for structured logging.
            user_id:         User identifier for audit / rate-limiting.
            max_tokens:      Max tokens to generate; None = provider default.
            temperature:     Sampling temperature; None = provider default.
            rag_context:     RAG document snippets already assembled by caller.

        Returns:
            Generated text string.

        Raises:
            LLMClientError: On unrecoverable failure.
        """

    @abstractmethod
    def stream(
        self,
        prompt: str,
        *,
        system_prompt: str = "",
        conversation_id: str | None = None,
        user_id: str | None = None,
        max_tokens: int | None = None,
        temperature: float | None = None,
        rag_context: list[str] | None = None,
    ) -> AsyncIterator[str]:
        """Stream response tokens incrementally.

        Args: Same as generate().

        Yields:
            Token strings as generated by the provider.

        Raises:
            LLMClientError: On unrecoverable failure (wrapped in the
                                 async generator body).
        """


# ---------------------------------------------------------------------------
# Adapters — wrap existing implementations without modifying them
# ---------------------------------------------------------------------------


class LLMServiceAdapter(LLMClient):
    """Wraps the existing :class:`~app.llm.service.LLMService` singleton.

    Bridges the agent LLMClient interface to the cloud LLM routing and
    fallback logic already implemented in LLMService.  **LLMService is not
    modified.**

    This adapter is created lazily so the heavy provider imports only happen
    when an agent actually calls the LLM.
    """

    def __init__(self) -> None:
        self._service: object | None = None

    def _get_service(self) -> object:
        if self._service is None:
            from app.llm.service import get_llm_service
            self._service = get_llm_service()
        return self._service

    @property
    def provider_name(self) -> str:
        return "gemini"

    @property
    def is_available(self) -> bool:
        # Optimistic: assume available; actual failures surface as exceptions
        return True

    async def generate(
        self,
        prompt: str,
        *,
        system_prompt: str = "",
        conversation_id: str | None = None,
        user_id: str | None = None,
        max_tokens: int | None = None,
        temperature: float | None = None,
        rag_context: list[str] | None = None,
    ) -> str:
        from app.llm.base import LLMRequest
        from app.llm.exceptions import LLMError

        req = LLMRequest(
            prompt=prompt,
            system_prompt=system_prompt,
            conversation_id=conversation_id,
            user_id=user_id,
            max_output_tokens=max_tokens,
            temperature=temperature,
            rag_context=rag_context or [],
        )
        try:
            svc = self._get_service()
            response = await svc.generate(req)  # type: ignore[attr-defined]
            return response.text
        except LLMError as exc:
            raise LLMClientError(
                str(exc),
                provider=self.provider_name,
                retryable=getattr(exc, "is_transient", False),
            ) from exc

    async def stream(  # type: ignore[override]
        self,
        prompt: str,
        *,
        system_prompt: str = "",
        conversation_id: str | None = None,
        user_id: str | None = None,
        max_tokens: int | None = None,
        temperature: float | None = None,
        rag_context: list[str] | None = None,
    ) -> AsyncIterator[str]:
        """Delegate streaming to LLMService (which delegates to GeminiProvider.stream)."""
        from app.llm.base import LLMRequest
        from app.llm.exceptions import LLMError

        req = LLMRequest(
            prompt=prompt,
            system_prompt=system_prompt,
            conversation_id=conversation_id,
            user_id=user_id,
            max_output_tokens=max_tokens,
            temperature=temperature,
            rag_context=rag_context or [],
        )
        try:
            svc = self._get_service()
            # LLMService.generate is used for non-streaming; for streaming we
            # call the resolved provider directly to get the async iterator.
            provider = svc._resolve_provider(req)  # type: ignore[attr-defined]
            async for token in provider.stream(req):
                yield token
        except LLMError as exc:
            raise LLMClientError(
                str(exc),
                provider=self.provider_name,
                retryable=getattr(exc, "is_transient", False),
            ) from exc


class LocalGemmaAdapter(LLMClient):
    """Wraps the existing :class:`~app.llm.providers.local_gemma_provider.LocalGemmaProvider`.

    Routes requests to a locally running Ollama Gemma model.
    **LocalGemmaProvider is not modified.**
    """

    def __init__(self, model_name: str = "gemma3:latest") -> None:
        self._model_name = model_name
        self._provider: object | None = None

    def _get_provider(self) -> object:
        if self._provider is None:
            from app.llm.providers.local_gemma_provider import LocalGemmaProvider
            self._provider = LocalGemmaProvider(model_name=self._model_name)
        return self._provider

    @property
    def provider_name(self) -> str:
        return "gemma"

    @property
    def is_available(self) -> bool:
        try:
            from app.config.settings import get_settings
            url = get_settings().OLLAMA_BASE_URL
            return bool(url and url.strip())
        except Exception:
            return False

    async def generate(
        self,
        prompt: str,
        *,
        system_prompt: str = "",
        conversation_id: str | None = None,
        user_id: str | None = None,
        max_tokens: int | None = None,
        temperature: float | None = None,
        rag_context: list[str] | None = None,
    ) -> str:
        from app.llm.base import LLMRequest
        from app.llm.exceptions import LLMError

        req = LLMRequest(
            prompt=prompt,
            system_prompt=system_prompt,
            conversation_id=conversation_id,
            user_id=user_id,
            max_output_tokens=max_tokens,
            temperature=temperature,
            rag_context=rag_context or [],
            complexity="local",
        )
        try:
            provider = self._get_provider()
            response = await provider.generate(req)  # type: ignore[attr-defined]
            return response.text
        except LLMError as exc:
            raise LLMClientError(
                str(exc), provider=self.provider_name, retryable=True
            ) from exc

    async def stream(  # type: ignore[override]
        self,
        prompt: str,
        *,
        system_prompt: str = "",
        conversation_id: str | None = None,
        user_id: str | None = None,
        max_tokens: int | None = None,
        temperature: float | None = None,
        rag_context: list[str] | None = None,
    ) -> AsyncIterator[str]:
        from app.llm.base import LLMRequest
        from app.llm.exceptions import LLMError

        req = LLMRequest(
            prompt=prompt,
            system_prompt=system_prompt,
            conversation_id=conversation_id,
            user_id=user_id,
            max_output_tokens=max_tokens,
            temperature=temperature,
            rag_context=rag_context or [],
            complexity="local",
        )
        try:
            provider = self._get_provider()
            async for token in provider.stream(req):  # type: ignore[attr-defined]
                yield token
        except LLMError as exc:
            raise LLMClientError(
                str(exc), provider=self.provider_name, retryable=True
            ) from exc

