# ─────────────────────────────────────────────────────────────────────────────
# environments/dev/terraform.tfvars
#
# Variable values for the DEV environment.
#
# HOW TO USE:
#   cd terraform
#   terraform init -backend-config="prefix=terraform/state/dev"
#   terraform plan  -var-file="environments/dev/terraform.tfvars"
#   terraform apply -var-file="environments/dev/terraform.tfvars"
#
# WHAT GOES HERE vs Secret Manager:
#   ✅ Non-sensitive config (project IDs, regions, instance counts)
#   ✅ OAuth client IDs (public values, not secrets)
#   ❌ API keys, passwords, tokens — those live in Secret Manager only
#   ❌ HMAC keys — generated by the storage module and auto-stored in Secret Manager
# ─────────────────────────────────────────────────────────────────────────────

# ── Project ───────────────────────────────────────────────────────────────────
project_id     = "android-ai-assistant-89cec"
project_number = "106071012091"
region         = "asia-south1"
environment    = "dev"

# ── Service account ───────────────────────────────────────────────────────────
backend_sa_name = "ai-assistant-backend"

# ── Storage ───────────────────────────────────────────────────────────────────
# Defaults to <project_id>-files — leave empty to use the default
storage_bucket_name = ""
storage_location    = "asia-south1"

# ── Artifact Registry ─────────────────────────────────────────────────────────
artifact_repo_name = "backend"

# ── Backend image ─────────────────────────────────────────────────────────────
# Set backend_image_tag to "latest" in dev; CI overrides this with a git SHA
backend_image     = "asia-south1-docker.pkg.dev/android-ai-assistant-89cec/backend/api"
backend_image_tag = "latest"

# ── Cloud Run — backend scaling (dev: scale to zero, max 1 to save cost) ─────
backend_min_instances = 0
backend_max_instances = 1
backend_cpu           = "1"
backend_memory        = "512Mi"
backend_concurrency   = 20

# ── Cloud Run — ChromaDB scaling ──────────────────────────────────────────────
chroma_image         = "chromadb/chroma:1.5.9"
chroma_min_instances = 0
chroma_max_instances = 1

# ── LLM config ────────────────────────────────────────────────────────────────
default_llm_provider  = "gemini"
llm_fallback_provider = "openai"

# Lower token limits in dev to keep LLM costs minimal during testing
llm_max_tokens_openai = 1024
llm_max_tokens_gemini = 2048
llm_max_tokens_claude = 1024

# ── OAuth client IDs (non-secret — safe to store here) ───────────────────────
google_client_id         = "106071012091-d4brm5cng1gaor0al51veafjd0fa239v.apps.googleusercontent.com"
google_android_client_id = "106071012091-0cu6q2e6b4tsa1qrauutqt70ms13otn6.apps.googleusercontent.com"

# ── Workload Identity Federation ──────────────────────────────────────────────
github_org  = "kotlinandfluttertutorial-lab"
github_repo = "Android-AI-Assistant-Test"
